name: Build docker image and push to registry # workflow for building and pushing Docker image & docker token updated
on:
  push:
    branches:
      - docker_CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true  # ➡️ adds the image to local Docker daemon
          tags: ${{ secrets.DOCKER_USERNAME }}/sysfoo_cart:v2

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: ${{ secrets.DOCKER_USERNAME }}/sysfoo_cart:v2
          format: 'table'
          output: trivy-report.txt
          exit-code: 0
          ignore-unfixed: true

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-report.txt

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sysfoo_cart:v2

      - name: Save Docker image as tar
        run: |
          docker save -o sysfoo_cart.tar ${{ secrets.DOCKER_USERNAME }}/sysfoo_cart:v2

      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysfoo_cart-image
          path: sysfoo_cart.tar
