name : CI pipeline
on:
  push:
    branches:
      - 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: MVN test
        run: mvn test
      - name: MVN Clean
        run:  mvn clean
      - name: MVN package
        run: mvn package
      - name: List WAR file in target directory
        run: |
          echo "Listing WAR files in target/"
          ls -lh target/*.war
      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devsecops-war
          path: target/devsecops.war
     
            

